name: Checks

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Tools
      run: pip install flake8 pytest
    - name: Flake8
      run: flake8
    - name: Tests
      run: echo "There are no tests yet"
