name: Checks

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Tools
      run: python3 -m pip install flake8 isort pytest setuptools
    - name: Install Dependencies
      run: python3 -m pip install -r requirements.txt
    - name: Flake8
      run: python3 -m flake8
    - name: Isort
      run: python3 -m isort --check-only -rc optprompt
    - name: Tests
      run: PYTHONPATH=. python3 -m pytest tests
